int menuEscolhas();
void swap(int* a, int* b);
void selectionSort(int n, int vet[]);
void incertionSort(int n, int vet[]);
void merge(int l, int m, int r, int vet[]);
void mergeSort(int l, int r, int vet[]);
void quickSort(int menor, int maior, int vet[]);
int parte(int menor, int maior, int vet[]);
int* criaVetorCrescente(int n, int* vet);
int* criaVetorDecrescente(int n);
